import { StyleSheet } from "@react-pdf/renderer";

export const adminDocPdfStyles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 10,
    color: "#17231f",
    fontFamily: "Helvetica",
    backgroundColor: "#fffdfa",
  },
  headerBand: {
    backgroundColor: "#0a3f39",
    color: "#f7f3ea",
    padding: 16,
    borderRadius: 8,
    marginBottom: 18,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 4,
  },
  headerMeta: {
    fontSize: 9,
    color: "#d8ece8",
  },
  sectionTitle: {
    fontSize: 12,
    color: "#0a3f39",
    fontWeight: 700,
    marginBottom: 8,
    marginTop: 10,
  },
  bodyText: {
    fontSize: 10,
    color: "#3f4f49",
    lineHeight: 1.5,
    marginBottom: 6,
  },
  stepCard: {
    border: "1px solid #d8ded7",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    backgroundColor: "#fffdfa",
  },
  stepBadge: {
    backgroundColor: "#0f5b52",
    color: "#f7f3ea",
    borderRadius: 999,
    width: 22,
    height: 22,
    textAlign: "center",
    fontSize: 11,
    fontWeight: 700,
    paddingTop: 4,
    marginBottom: 8,
  },
  stepTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "#0a3f39",
    marginBottom: 6,
  },
  screenFrame: {
    border: "1px solid #d8ded7",
    borderRadius: 8,
    overflow: "hidden",
    marginTop: 8,
    marginBottom: 4,
  },
  screenBar: {
    backgroundColor: "#e2eeea",
    padding: 6,
    fontSize: 8,
    color: "#0a3f39",
  },
  screenBody: {
    backgroundColor: "#f7f3ea",
    padding: 12,
  },
  screenCard: {
    backgroundColor: "#fffdfa",
    border: "1px solid #d8ded7",
    borderRadius: 6,
    padding: 10,
  },
  screenEyebrow: {
    fontSize: 7,
    color: "#5f6f68",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  screenHeading: {
    fontSize: 12,
    fontWeight: 700,
    color: "#17231f",
    marginBottom: 4,
  },
  screenMuted: {
    fontSize: 8,
    color: "#5f6f68",
    marginBottom: 8,
  },
  fieldLabel: {
    fontSize: 8,
    color: "#17231f",
    marginBottom: 2,
  },
  fieldBox: {
    border: "1px solid #d8ded7",
    borderRadius: 4,
    padding: 6,
    marginBottom: 6,
    fontSize: 8,
    color: "#5f6f68",
    backgroundColor: "#fffdfa",
  },
  primaryButton: {
    backgroundColor: "#0a3f39",
    color: "#f7f3ea",
    borderRadius: 999,
    padding: 6,
    fontSize: 8,
    textAlign: "center",
    marginTop: 2,
  },
  checklistItem: {
    fontSize: 9,
    color: "#3f4f49",
    marginBottom: 4,
  },
  footerNote: {
    marginTop: 14,
    fontSize: 8,
    color: "#5f6f68",
    borderTop: "1px solid #e2eeea",
    paddingTop: 8,
  },
});
